[package]
name = "event-correlator"
version = "0.1.0"
edition = "2021"

[lib]
name = "event_correlator"
crate-type = ["cdylib"]

#[[bin]]
#name = "sudoku"
## crate-type = ["cdylib"]

[dependencies]
indicatif = "0.17.7"
itertools = "0.12.0"
pyo3 = "0.20.2"
